#!/usr/bin/ruby

#
# this file runs django tests for the nedge plugin
#

require 'json'

if 1 != ARGV.length
  puts "Usage: ./jenkins_tests x.x.x.x:8080"
  puts "where x.x.x.x is the IP of the machine running the rest worker."
  puts "The rest worker should be available on port 8080."
  exit 3
end

def puts! args, label=""
  puts "+++ +++ #{label}"
  puts args.inspect
end

nedge_url = ARGV[0]

# write spec config
File.open('tests/test_config.json', 'w') do |f|
  f.write( { :nedge_url => nedge_url }.to_json )
end

# launch
` cd ../../../ && ./run_tests.sh openstack_dashboard.dashboards.horizon_nedge_dashboard `
exit_status =  $?.exitstatus
puts! exit_status, "Exit status of django tests"


exit exit_status
